### ISSUE TITLE
Churro 2.0

### ISSUE THREAD

**Issue by alberto-lad** [jesi-rgb/tractor2.0#2]
The unwind was generating problems due to the createdAt column (there is a createdAt for the tweet, and another one for the user. After unwinding, the tweet createdAt is removed, loosing key info).

- modify the previous omit and unwind parts of the churro:
`&omit=id,type,twitterUrl,inReplyToId,inReplyToUserId,inReplyToUsername,extendedEntities,card,place,entities,quote,quoteId,isConversationControlled,coverPicture,status,canDm,canMediaTag,fastFollowersCount,hasCustomTimelines,isTranslator,withheldInCountries,affiliatesHighlightedLabel&unwind=author`
- for this new version:
`&omit=id,type,twitterUrl,inReplyToId,inReplyToUserId,inReplyToUsername,extendedEntities,card,place,entities,quote,quoteId,isConversationControlled`

**Comment by jesi-rgb** [comment]
so, as I can see, we are omitting less stuff, but we are no longer unwinding. that will create an "author" column whose contents are a json object, right?

**Comment by alberto-lad** [comment]
we are not unwinding the author column. As soon as it's unwinded, it overwrites _createdAt_ for the tweet.
Instead, the dataset can be processed later with methods like:

extract_json_values(ds.author, {
    "path": "followers",
    "type": "number"
}) -> (ds.followers)

Another method could be extracting the createdAt of the tweet from the id, but the id formatting has changed multiple time, generating problems with consistency.

**Comment by jesi-rgb** [comment]
gotchu, so we are going to unwind the author later in graphext

**Comment by jesi-rgb** [comment]
i wonder what these can be used for?

`coverPicture,status,canDm,canMediaTag,fastFollowersCount,hasCustomTimelines,isTranslator,withheldInCountries,affiliatesHighlightedLabel`

these are the columns you removed from the original url, that we'd be keeping now

do we need `withheldInCountries`? `fastFollowersCount`?

**Comment by alberto-lad** [comment]
These columns are a result of the unwind.
We cant omit them since we aren't unwinding the author column, therefore they don't "exist".
Instead of omiting them, we will only use extract_json_values with the columns we need
